services:
  - type: web
    name: atrowave-payment-gateway
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: atrowave-db
          property: connectionString
      - key: FLUTTERWAVE_BASE_URL
        value: https://api.flutterwave.com/v3
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: BYBIT_BASE_URL
        value: https://api.bybit.com
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false

databases:
  - name: atrowave-db
    databaseName: payment_gateway
    user: atrowave_user
